### PR TITLE
MOB-1576 GRPC Build error on x86_64 Android

### PR DESCRIPTION
**Pull request by junggyu-sc**
in crux-lib-deps,
run 'make build_android' ends up building error for grpc/x86_64 because GPR_MUSL_LIBC_COMPAT is not defined in grpc.

Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/bits/fortify/string.h:62: error: undefined reference to 'memcpy', version 'GLIBC_2.2.5'

### CODE REVIEW

**Comment by codingrhythm** [comment]
Hi @junggyu-sc I think this is the branch that `crux-lib-deps` is using. https://github.com/SafetyCulture/grpc/tree/crux-v1.30.x also, should we consider just upgrade gRPC to the latest version?

**Comment by junggyu-sc** [comment]
right, I thought it was master but actually it is v1.30.x. I think the above macro is not defined in the latest master of GRPC so upgrading will not fix the issue.

**Comment by codingrhythm** [comment]
That's correct. I was trying to say should we also upgrade gRPC as well.

**Comment by junggyu-sc** [comment]
this PR is going to be replaced with new one (based on crux-1.40.0).

**Pull request closed without merging**
